# Generated by Django 5.2.15 on 2026-07-02 16:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('number', models.CharField(editable=False, max_length=12, unique=True, verbose_name='رقم الطلب')),
                ('customer_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^09\\d{8}$', 'أدخل رقم موبايل سوري صحيح: 09 يتبعها 8 أرقام.')], verbose_name='رقم الموبايل')),
                ('city', models.CharField(max_length=50, verbose_name='المحافظة / المدينة')),
                ('address', models.TextField(verbose_name='العنوان بالتفصيل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('payment_method', models.CharField(choices=[('cod', 'الدفع عند الاستلام'), ('shamcash', 'شام كاش')], default='cod', max_length=10, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'بانتظار التأكيد'), ('confirmed', 'مؤكّد'), ('shipped', 'قيد التوصيل'), ('delivered', 'مُسلَّم'), ('cancelled', 'ملغى')], default='pending', max_length=10, verbose_name='الحالة')),
                ('total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='الإجمالي (ل.س)')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='اسم المنتج وقت الطلب')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='سعر القطعة وقت الطلب (ل.س)')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'سطر طلب',
                'verbose_name_plural': 'أسطر الطلب',
            },
        ),
    ]
