# Generated by Django 5.2.15 on 2026-07-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='المحافظة')),
                ('fee', models.DecimalField(blank=True, decimal_places=0, help_text='اتركه فارغاً = «يُتفق هاتفياً». صفر = توصيل مجاني.', max_digits=12, null=True, verbose_name='رسم التوصيل (ل.س)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'منطقة توصيل',
                'verbose_name_plural': 'مناطق التوصيل',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='رسم التوصيل (ل.س)'),
        ),
    ]
