# Generated by Django 5.2.15 on 2026-07-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_seed_delivery_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('code', models.CharField(help_text='يُخزَّن بأحرف كبيرة تلقائياً — الزبون يكتبه بأي شكل.', max_length=20, unique=True, verbose_name='الكود')),
                ('kind', models.CharField(choices=[('percent', 'نسبة مئوية %'), ('fixed', 'مبلغ ثابت (ل.س)')], default='percent', max_length=10, verbose_name='النوع')),
                ('value', models.DecimalField(decimal_places=0, help_text='نسبة (1-100) أو مبلغ بالليرة حسب النوع.', max_digits=12, verbose_name='القيمة')),
                ('min_order_total', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='الحد الأدنى للمنتجات (ل.س)')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='فارغ = بلا حد.', null=True, verbose_name='حد الاستخدامات')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='استُخدم')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'كوبون',
                'verbose_name_plural': 'الكوبونات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='كود الخصم'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قيمة الخصم (ل.س)'),
        ),
    ]
