# Generated by Django 5.2.16 on 2026-07-25 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_brand_product_sku_product_brand_productoption_and_more"),
        ("orders", "0005_coupon_order_coupon_code_order_discount_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="catalog.productvariant",
                verbose_name="المقاس/اللون",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant_label",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="التركيبة وقت الطلب"
            ),
        ),
    ]
