# Generated by Django 5.2.15 on 2026-07-04 02:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('store_name', models.CharField(max_length=100, unique=True, verbose_name='اسم المتجر')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^09\\d{8}$', 'أدخل رقم موبايل سوري صحيح: 09 يتبعها 8 أرقام.')], verbose_name='موبايل التواصل')),
                ('city', models.CharField(max_length=50, verbose_name='المحافظة / المدينة')),
                ('description', models.TextField(blank=True, help_text='شو بتبيعوا؟ من متى وأنتم شغالين؟', verbose_name='عن المتجر')),
                ('is_approved', models.BooleanField(default=False, help_text='لا يستطيع التاجر إدارة منتجاته قبل الموافقة.', verbose_name='مقبول')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تاجر',
                'verbose_name_plural': 'التجار',
                'ordering': ['is_approved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('role', models.CharField(choices=[('customer', 'زبون'), ('merchant', 'تاجر')], default='customer', max_length=10, verbose_name='الدور')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^09\\d{8}$', 'أدخل رقم موبايل سوري صحيح: 09 يتبعها 8 أرقام.')], verbose_name='رقم الموبايل')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='المحافظة / المدينة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف شخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
    ]
