# Generated by Django 5.2.15 on 2026-07-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='يُولّد تلقائياً من الاسم إذا تُرك فارغاً.', max_length=120, unique=True, verbose_name='المعرّف بالرابط')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('parent', models.ForeignKey(blank=True, help_text='اتركه فارغاً ليكون تصنيفاً رئيسياً.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='التصنيف الأب')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='يُولّد تلقائياً من الاسم إذا تُرك فارغاً.', max_length=220, unique=True, verbose_name='المعرّف بالرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=0, help_text='بالليرة السورية، بدون كسور.', max_digits=12, verbose_name='السعر (ل.س)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='الكمية بالمخزون')),
                ('is_active', models.BooleanField(default=True, help_text='المنتج غير المفعّل لا يظهر بالمتجر إطلاقاً.', verbose_name='مفعّل')),
                ('specs', models.JSONField(blank=True, default=dict, help_text='مواصفات حرّة بصيغة JSON، مثال: {"اللون": "أسود", "الضمان": "سنة"}', verbose_name='المواصفات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أُنشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='الصورة')),
                ('alt_text', models.CharField(blank=True, help_text='وصف قصير للصورة (يفيد لضعاف البصر ومحركات البحث).', max_length=200, verbose_name='النص البديل')),
                ('is_main', models.BooleanField(default=False, verbose_name='رئيسية')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتجات',
                'ordering': ['-is_main', 'sort_order', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_category_name_per_parent'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category'], name='catalog_pro_is_acti_1a8de5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='catalog_pro_created_eee82f_idx'),
        ),
    ]
