# Generated by Django 5.2.15 on 2026-07-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_backfill_search_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='اختياري: إن وُضع وكان أعلى من السعر، يظهر المنتج «بالتخفيضات» مع السعر القديم مشطوباً.', max_digits=12, null=True, verbose_name='السعر قبل التخفيض (ل.س)'),
        ),
    ]
