# Generated by Django 5.2.15 on 2026-07-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_compare_at_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumb',
            field=models.ImageField(blank=True, editable=False, upload_to='products/thumbs/%Y/%m/', verbose_name='المصغّرة'),
        ),
    ]
