# Generated by Django 5.2.15 on 2026-07-04 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0006_backfill_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ForeignKey(blank=True, help_text='اتركه فارغاً إذا المنتج من بضاعة الصَّيَّاد مباشرة.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='accounts.merchantprofile', verbose_name='البائع'),
        ),
    ]
