# Generated by Django 5.2.16 on 2026-07-25 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="الاسم"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="يُولّد تلقائياً من الاسم إذا تُرك فارغاً.",
                        max_length=120,
                        unique=True,
                        verbose_name="المعرّف بالرابط",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="مفعّلة")),
            ],
            options={
                "verbose_name": "ماركة",
                "verbose_name_plural": "الماركات",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="رمزك الداخلي للجرد — اختياري، ويظهر بالبحث.",
                max_length=40,
                verbose_name="رمز المنتج (SKU)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                help_text="اتركها فارغة إذا المنتج بلا ماركة معروفة.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.brand",
                verbose_name="الماركة",
            ),
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="مثال: المقاس، اللون، السعة.",
                        max_length=50,
                        verbose_name="اسم الخيار",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="catalog.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "خيار منتج",
                "verbose_name_plural": "خيارات المنتج",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ProductOptionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                ("value", models.CharField(max_length=50, verbose_name="القيمة")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="لترتيب المقاسات منطقياً (S ثم M ثم L) لا أبجدياً.",
                        verbose_name="الترتيب",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="catalog.productoption",
                        verbose_name="الخيار",
                    ),
                ),
            ],
            options={
                "verbose_name": "قيمة خيار",
                "verbose_name_plural": "قيم الخيارات",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="أُنشئ في"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تعديل"),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="رمز المتغيّر (SKU)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="اتركه فارغاً ليأخذ سعر المنتج. املأه فقط إذا هذا المقاس/اللون بسعر مختلف.",
                        max_digits=12,
                        null=True,
                        verbose_name="سعر خاص (ل.س)",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="الكمية بالمخزون"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="أزل التفعيل لإخفاء هذه التركيبة دون حذف سجلّها.",
                        verbose_name="مفعّل",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                        verbose_name="المنتج",
                    ),
                ),
                (
                    "value_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants_as_first",
                        to="catalog.productoptionvalue",
                        verbose_name="الخيار الأول",
                    ),
                ),
                (
                    "value_2",
                    models.ForeignKey(
                        blank=True,
                        help_text="اتركه فارغاً إذا للمنتج خيار واحد فقط.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants_as_second",
                        to="catalog.productoptionvalue",
                        verbose_name="الخيار الثاني",
                    ),
                ),
            ],
            options={
                "verbose_name": "متغيّر منتج",
                "verbose_name_plural": "متغيّرات المنتج",
                "ordering": ["value_1__sort_order", "value_2__sort_order", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="productoption",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="uniq_option_name_per_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="productoptionvalue",
            constraint=models.UniqueConstraint(
                fields=("option", "value"), name="uniq_value_per_option"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("value_2__isnull", False)),
                fields=("product", "value_1", "value_2"),
                name="uniq_variant_two_axis",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("value_2__isnull", True)),
                fields=("product", "value_1"),
                name="uniq_variant_one_axis",
            ),
        ),
    ]
